version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    restart: unless-stopped
  db:
    image: mysql:5.7
    ports:
      - "3303:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: newuser 
      MYSQL_PASSWORD: newpassword
      MYSQL_DATABASE: classicmodels
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - .:/app
