version: "3"
services:
  app:
      build: ./app
      command: gunicorn -w 4 --bind 0.0.0.0:5000 app:app 
      #command: python app.py run -h 0.0.0.0:5000
      volumes:
        - ./app/:/user/src/app/
      expose:
        - "5000"
      ports:
        - "5000:5000"
      depends_on:
        - db
      links:
        - db
      restart: unless-stopped
      healthcheck:
        test: curl --fail -s http://localhost:5000/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
      networks:
        - frontend
        - backend
      # image: solomoon67/docker-sql_app:latest

  db:
    image: mysql:5.7
    expose:
      # Opens port 3306 on the container
      - "3306"
    ports:
      - "3000:3306"
    env_file:
      - ./.env.prod.db
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_USER: newuser 
    #   MYSQL_PASSWORD: newpassword
    #   MYSQL_DATABASE: classicmodels
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - .:/app
    healthcheck:
      test: curl --fail -s http://localhost:3306/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      - backend
    # image: solomoon67/docker-sql_app:latest

  server:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        expose:
            - "8080"
        ports:
            - "80:8080"
        depends_on:
            - app
        networks:
            - backend
        # image: solomoon67/docker-sql_app:latest
      
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

